services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n-aula
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.local
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - /home/natanael-figueredo-balbo/n8n:/home/node/.n8n
    restart: always

  waha:
    image: devlikeapro/waha
    ports:
      - "3000:3000"
    environment:
      - WAHA_PORT=3000
      - WAHA_LOG_LEVEL=info
      - WHATSAPP_DEFAULT_ENGINE=${WHATSAPP_DEFAULT_ENGINE}
      - WHATSAPP_HOOK_EVENTS=${WHATSAPP_HOOK_EVENTS}
      - WHATSAPP_HOOK_URL=${WHATSAPP_HOOK_URL}
      - NODE_OPTIONS=--no-deprecation
      - WAHA_DASHBOARD_ENABLED=true
      - WAHA_DASHBOARD_USERNAME=waha
      - WAHA_DASHBOARD_PASSWORD=waha
    volumes:
      - /home/natanael-figueredo-balbo/waha:/tmp/
    restart: always

volumes:
  waha_data: