services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5679:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_LISTEN_ADDRESS=0.0.0.0
      - N8N_EDITOR_BASE_URL=http://localhost:5679
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - /home/natanael-figueredo-balbo/n8n:/home/node/.n8n
    restart: always
    networks:
      - waha-network

  waha:
    image: devlikeapro/waha
    container_name: waha
    ports:
      - "3001:3000"
    environment:
      - WAHA_PORT=3000
      - WAHA_LOG_LEVEL=info
      - WHATSAPP_DEFAULT_ENGINE=${WHATSAPP_DEFAULT_ENGINE}
      - WHATSAPP_HOOK_EVENTS=${WHATSAPP_HOOK_EVENTS}
      - WHATSAPP_HOOK_URL=${WHATSAPP_HOOK_URL}
      - NODE_OPTIONS=--no-deprecation
      - WAHA_DASHBOARD_ENABLED=${WAHA_DASHBOARD_ENABLED}
      - WAHA_DASHBOARD_USERNAME=${WAHA_DASHBOARD_USERNAME}
      - WAHA_DASHBOARD_PASSWORD=${WAHA_DASHBOARD_PASSWORD}
    volumes:
      - /home/natanael-figueredo-balbo/waha:/tmp/
    restart: always
    depends_on:
      - n8n
    networks:
      - waha-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  waha_data:

networks:
  waha-network:
    driver: bridge